### ISSUE TITLE
AttributeError in current code base

### ISSUE THREAD

**Issue by timmie** [rochacbruno-archive/Movuca#21]
''''
Traceback (most recent call last):
  File "/opt/source/webdev/web2py_github/gluon/restricted.py", line 205, in restricted
    exec ccode in environment
  File "/opt/source/webdev/web2py_github/applications/Movuca/controllers/default.py", line 90, in <module>
  File "/opt/source/webdev/web2py_github/gluon/globals.py", line 182, in <lambda>
    self._caller = lambda f: f()
  File "/opt/source/webdev/web2py_github/applications/Movuca/controllers/default.py", line 18, in index
    home = Home(['featured', 'featured_members', 'ads', 'homeblocks', 'articles'])
  File "applications/Movuca/modules/handlers/base.py", line 32, in __init__
    self.start()
  File "applications/Movuca/modules/handlers/home.py", line 12, in start
    self.db = DataBase([User, ContentType, Category, Article, Ads, Page])
  File "applications/Movuca/modules/movuca.py", line 31, in **init**
    DAL.**init**(self, self.config.db.uri,
AttributeError: 'NoneType' object has no attribute 'uri'

''''

**Comment by timmie** [comment]
Page:
http://127.0.0.1:8000/Movuca/default/index

git clone of just now.
